// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

// Student is the golang structure for table student.
type Student struct {
	Id        int64  `orm:"id,primary" json:"id"`        // 学生编号
	Name      string `orm:"name"       json:"name"`      // 学生姓名
	Gender    string `orm:"gender"     json:"gender"`    // 学生性别
	Stuid     string `orm:"stuid"      json:"stuid"`     // 学生学号
	Password  string `orm:"password"   json:"password"`  // 学生密码
	Email     string `orm:"email"      json:"email"`     // 学生邮箱
	Introduce string `orm:"introduce"  json:"introduce"` // 学生简介
}
