// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"team-gf/app/dao/internal"
)

// studentDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type studentDao struct {
	*internal.StudentDao
}

var (
	// Student is globally public accessible object for table student operations.
	Student = studentDao{
		internal.NewStudentDao(),
	}
)

// Fill with you ideas below.
