// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"team-gf/app/dao/internal"
)

// teacherDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type teacherDao struct {
	*internal.TeacherDao
}

var (
	// Teacher is globally public accessible object for table teacher operations.
	Teacher = teacherDao{
		internal.NewTeacherDao(),
	}
)

// Fill with you ideas below.
