// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// TeacherDao is the manager for logic model data accessing and custom defined data operations functions management.
type TeacherDao struct {
	Table   string         // Table is the underlying table name of the DAO.
	Group   string         // Group is the database configuration group name of current DAO.
	Columns TeacherColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// TeacherColumns defines and stores column names for table teacher.
type TeacherColumns struct {
	Id        string // 老师编号
	Name      string // 老师姓名
	Gender    string // 老师性别
	Phone     string // 老师手机号
	Email     string // 老师邮箱
	Introduce string // 老师简介
}

//  teacherColumns holds the columns for table teacher.
var teacherColumns = TeacherColumns{
	Id:        "id",
	Name:      "name",
	Gender:    "gender",
	Phone:     "phone",
	Email:     "email",
	Introduce: "introduce",
}

// NewTeacherDao creates and returns a new DAO object for table data access.
func NewTeacherDao() *TeacherDao {
	return &TeacherDao{
		Group:   "default",
		Table:   "teacher",
		Columns: teacherColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TeacherDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TeacherDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TeacherDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
