// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// TeamDao is the manager for logic model data accessing and custom defined data operations functions management.
type TeamDao struct {
	Table   string      // Table is the underlying table name of the DAO.
	Group   string      // Group is the database configuration group name of current DAO.
	Columns TeamColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// TeamColumns defines and stores column names for table team.
type TeamColumns struct {
	Id        string // 编号
	Introduce string // 简介
	Game      string // 比赛名
}

//  teamColumns holds the columns for table team.
var teamColumns = TeamColumns{
	Id:        "id",
	Introduce: "introduce",
	Game:      "game",
}

// NewTeamDao creates and returns a new DAO object for table data access.
func NewTeamDao() *TeamDao {
	return &TeamDao{
		Group:   "default",
		Table:   "team",
		Columns: teamColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TeamDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TeamDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TeamDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
